/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AvailableCommunity {
    #[serde(rename = "community")]
    pub community: Box<crate::models::Community>,
    #[serde(rename = "categories")]
    pub categories: Vec<crate::models::PackageCategory>,
    #[serde(rename = "url")]
    pub url: String,
}

impl AvailableCommunity {
    pub fn new(community: crate::models::Community, categories: Vec<crate::models::PackageCategory>, url: String) -> AvailableCommunity {
        AvailableCommunity {
            community: Box::new(community),
            categories,
            url,
        }
    }
}


