/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommunityPackageList {
    #[serde(rename = "bg_image_src")]
    pub bg_image_src: Option<String>,
    #[serde(rename = "categories")]
    pub categories: Vec<crate::models::PackageCategory>,
    #[serde(rename = "community_name")]
    pub community_name: String,
    #[serde(rename = "has_more_pages")]
    pub has_more_pages: bool,
    #[serde(rename = "packages")]
    pub packages: Vec<crate::models::PackageCard>,
}

impl CommunityPackageList {
    pub fn new(bg_image_src: Option<String>, categories: Vec<crate::models::PackageCategory>, community_name: String, has_more_pages: bool, packages: Vec<crate::models::PackageCard>) -> CommunityPackageList {
        CommunityPackageList {
            bg_image_src,
            categories,
            community_name,
            has_more_pages,
            packages,
        }
    }
}


