/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FrontPageContent {
    #[serde(rename = "communities")]
    pub communities: Vec<crate::models::CommunityCard>,
    #[serde(rename = "download_count")]
    pub download_count: u32,
    #[serde(rename = "package_count")]
    pub package_count: u32,
}

impl FrontPageContent {
    pub fn new(communities: Vec<crate::models::CommunityCard>, download_count: u32, package_count: u32) -> FrontPageContent {
        FrontPageContent {
            communities,
            download_count,
            package_count,
        }
    }
}


