/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ManifestV1ValidatorParams {
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "manifest_data")]
    pub manifest_data: String,
}

impl ManifestV1ValidatorParams {
    pub fn new(namespace: String, manifest_data: String) -> ManifestV1ValidatorParams {
        ManifestV1ValidatorParams {
            namespace,
            manifest_data,
        }
    }
}


