/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PackageSubmissionMetadata {
    #[serde(rename = "author_name")]
    pub author_name: String,
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
    #[serde(rename = "communities")]
    pub communities: Vec<String>,
    #[serde(rename = "has_nsfw_content")]
    pub has_nsfw_content: bool,
    #[serde(rename = "upload_uuid")]
    pub upload_uuid: uuid::Uuid,
}

impl PackageSubmissionMetadata {
    pub fn new(author_name: String, categories: Vec<String>, communities: Vec<String>, has_nsfw_content: bool, upload_uuid: uuid::Uuid) -> PackageSubmissionMetadata {
        PackageSubmissionMetadata {
            author_name,
            categories,
            communities,
            has_nsfw_content,
            upload_uuid,
        }
    }
}


