/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PackageVersionExperimental {
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version_number")]
    pub version_number: String,
    #[serde(rename = "full_name", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "dependencies", skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<String>,
    #[serde(rename = "download_url", skip_serializing_if = "Option::is_none")]
    pub download_url: Option<String>,
    #[serde(rename = "downloads", skip_serializing_if = "Option::is_none")]
    pub downloads: Option<u32>,
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    #[serde(rename = "website_url")]
    pub website_url: String,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl PackageVersionExperimental {
    pub fn new(name: String, version_number: String, description: String, website_url: String) -> PackageVersionExperimental {
        PackageVersionExperimental {
            namespace: None,
            name,
            version_number,
            full_name: None,
            description,
            icon: None,
            dependencies: None,
            download_url: None,
            downloads: None,
            date_created: None,
            website_url,
            is_active: None,
        }
    }
}


