/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PackageExperimental {
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "full_name", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    #[serde(rename = "package_url", skip_serializing_if = "Option::is_none")]
    pub package_url: Option<String>,
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    #[serde(rename = "rating_score", skip_serializing_if = "Option::is_none")]
    pub rating_score: Option<String>,
    #[serde(rename = "is_pinned", skip_serializing_if = "Option::is_none")]
    pub is_pinned: Option<bool>,
    #[serde(rename = "is_deprecated", skip_serializing_if = "Option::is_none")]
    pub is_deprecated: Option<bool>,
    #[serde(rename = "total_downloads", skip_serializing_if = "Option::is_none")]
    pub total_downloads: Option<String>,
    #[serde(rename = "latest")]
    pub latest: Box<crate::models::PackageVersionExperimental>,
    #[serde(rename = "community_listings")]
    pub community_listings: Vec<crate::models::PackageListingExperimental>,
}

impl PackageExperimental {
    pub fn new(name: String, latest: crate::models::PackageVersionExperimental, community_listings: Vec<crate::models::PackageListingExperimental>) -> PackageExperimental {
        PackageExperimental {
            namespace: None,
            name,
            full_name: None,
            owner: None,
            package_url: None,
            date_created: None,
            date_updated: None,
            rating_score: None,
            is_pinned: None,
            is_deprecated: None,
            total_downloads: None,
            latest: Box::new(latest),
            community_listings,
        }
    }
}


