/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PackageDetailViewContent {
    #[serde(rename = "bg_image_src")]
    pub bg_image_src: Option<String>,
    #[serde(rename = "categories")]
    pub categories: Vec<crate::models::PackageCategory>,
    #[serde(rename = "community_identifier")]
    pub community_identifier: String,
    #[serde(rename = "community_name")]
    pub community_name: String,
    #[serde(rename = "dependant_count")]
    pub dependant_count: u32,
    #[serde(rename = "dependencies")]
    pub dependencies: Vec<crate::models::PackageDependency>,
    #[serde(rename = "dependency_string")]
    pub dependency_string: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "download_count")]
    pub download_count: u32,
    #[serde(rename = "download_url")]
    pub download_url: String,
    #[serde(rename = "image_src")]
    pub image_src: Option<String>,
    #[serde(rename = "install_url")]
    pub install_url: String,
    #[serde(rename = "last_updated")]
    pub last_updated: String,
    #[serde(rename = "markdown")]
    pub markdown: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "package_name")]
    pub package_name: String,
    #[serde(rename = "rating_score")]
    pub rating_score: u32,
    #[serde(rename = "team_name")]
    pub team_name: String,
    #[serde(rename = "versions")]
    pub versions: Vec<crate::models::PackageVersion>,
    #[serde(rename = "website")]
    pub website: String,
}

impl PackageDetailViewContent {
    pub fn new(bg_image_src: Option<String>, categories: Vec<crate::models::PackageCategory>, community_identifier: String, community_name: String, dependant_count: u32, dependencies: Vec<crate::models::PackageDependency>, dependency_string: String, description: String, download_count: u32, download_url: String, image_src: Option<String>, install_url: String, last_updated: String, markdown: String, namespace: String, package_name: String, rating_score: u32, team_name: String, versions: Vec<crate::models::PackageVersion>, website: String) -> PackageDetailViewContent {
        PackageDetailViewContent {
            bg_image_src,
            categories,
            community_identifier,
            community_name,
            dependant_count,
            dependencies,
            dependency_string,
            description,
            download_count,
            download_url,
            image_src,
            install_url,
            last_updated,
            markdown,
            namespace,
            package_name,
            rating_score,
            team_name,
            versions,
            website,
        }
    }
}


