/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReadmeValidatorParams {
    #[serde(rename = "readme_data")]
    pub readme_data: String,
}

impl ReadmeValidatorParams {
    pub fn new(readme_data: String) -> ReadmeValidatorParams {
        ReadmeValidatorParams {
            readme_data,
        }
    }
}


