/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RenderMarkdownParams {
    #[serde(rename = "markdown")]
    pub markdown: String,
}

impl RenderMarkdownParams {
    pub fn new(markdown: String) -> RenderMarkdownParams {
        RenderMarkdownParams {
            markdown,
        }
    }
}


