/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestBody {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "redirect_uri")]
    pub redirect_uri: String,
}

impl RequestBody {
    pub fn new(code: String, redirect_uri: String) -> RequestBody {
        RequestBody {
            code,
            redirect_uri,
        }
    }
}


