/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserMediaFinishUploadParams {
    #[serde(rename = "parts")]
    pub parts: Vec<crate::models::CompletedPart>,
}

impl UserMediaFinishUploadParams {
    pub fn new(parts: Vec<crate::models::CompletedPart>) -> UserMediaFinishUploadParams {
        UserMediaFinishUploadParams {
            parts,
        }
    }
}


